### PR TITLE
Adding bucket option to aws_cdn.get_file

### PR DESCRIPTION
**Pull request by cluxton**
Adds a parameter to specify a bucket when getting an aws file.

### CODE REVIEW

**Comment by ian-axelrod** [comment]
Don't forget to bump the oz version and fix cci tests. (Actually, why is oz running cci?)

**Comment by ysimonson** [comment]
@ian-axelrod a misconfiguration, it should not be running it

**Comment by ian-axelrod** [comment]
This happens every so often. I wonder why CCI is re-adding its webhook to oz.

**Comment by ian-axelrod** [comment]
I've removed CCI.

**Pull request merged**
