### PR TITLE
Add support for creating a SSL connection to redis

### PR DESCRIPTION
**Pull request by ian-axelrod**
Adds ssl and friends to redis options.

### CODE REVIEW

**Comment by ian-axelrod** [comment]
Performing a few tests before merging. Also, is it normal for travis-ci to be failing?

**Comment by ysimonson** [comment]
shouldn't be, though it seems like there's an issue with boto

**Comment by ian-axelrod** [comment]
Looks to be completely unrelated

**Comment by ian-axelrod** [comment]
Merging, but will take a look at the tests shortly.

**Pull request merged**
